Traceback (most recent call last):
  File "/opt/miniconda3/envs/pythoncc/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/miniconda3/envs/pythoncc/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/miniconda3/envs/pythoncc/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/miniconda3/envs/pythoncc/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/miniconda3/envs/pythoncc/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/miniconda3/envs/pythoncc/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/miniconda3/envs/pythoncc/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#print 'ca' collumn from df
print('"Ca" column: ')
print(df['ca'])

#count number of NaN values in 'ca' collumn
print(f'Number of Nan values in "ca": {df['ca'].isna().sum()}')

# count number of unique values in 'ca' collumn
print(f'Number of unique values in "ca": {df['ca'].nunique()}')
# print the unique values in 'ca' collumn
print(f'Unique values in "ca": {df['ca'].unique()}')

# print data type of 'ca' from the variables_information
print(f'Data type of "ca": {variables_information[variables_information["name"] == "ca"]["type"].values[0]}')


#print 'thal' collumn from df
print('"Thal" column: ')
print(df['thal'])

#count number of NaN values in 'thal' collumn
print(f'Number of Nan values in "thal": {df['thal'].isna().sum()}')

# count number of unique values in 'thal' collumn
print(f'Number of unique values in "thal": {df['thal'].nunique()}')
# print the unique values in 'thal' collumn
print(f'Unique values in "thal": {df['thal'].unique()}')

# print data type of 'thal' from the variables_information
print(f'Data type of "thal": {variables_information[variables_information["name"] =="thal"]["type"].values[0]}')
------------------


[0;36m  Cell [0;32mIn[6], line 6[0;36m[0m
[0;31m    print(f'Number of Nan values in "ca": {df['ca'].isna().sum()}')[0m
[0m                                               ^[0m
[0;31mSyntaxError[0m[0;31m:[0m f-string: unmatched '['


